name: YzPlugin
main: org.thzs.YzPlugin
version: 0.1
author: thzs
commands:
  yz:
    description: 这是这个插件的开始符号
    usage: /yz
    permissions:
      yz.editor:
        description: 允许编辑
        default: op
      yz.use:
        description: 允许使用
        default: true